name: Test
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    permissions:
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install step
        run: "deno install"

      - name: Check Format
        run: "deno fmt --check"

      - name: Check Lint
        run: "deno lint"

      - name: Type Check
        run: "deno task check"
